#!/usr/bin/env python3
"""Simple SonarLint analysis script."""

import json
import subprocess
import sys
import time
from pathlib import Path

# this script is generated by Claude Code and it is used to analyze a Python file using SonarLint LSP server with simplified protocol.

def analyze_file_simple(file_path):
    """Analyze a Python file using SonarLint LSP server with simplified protocol."""
    project_root = Path(__file__).parent.parent
    jar_path = project_root / "binaries" / "sonarlint-language-server-4.13-SNAPSHOT.jar"
    analyzer_path = project_root / "binaries" / "sonarpython.jar"

    file_path = Path(file_path).resolve()
    file_uri = f"file://{file_path}"

    # Start LSP server
    cmd = [
        "java", "-jar", str(jar_path),
        "-stdio",
        "-analyzers", str(analyzer_path)
    ]

    process = subprocess.Popen(
        cmd,
        stdin=subprocess.PIPE,
        stdout=subprocess.PIPE,
        stderr=subprocess.PIPE,
        text=True,
        bufsize=1
    )

    def send_request(request):
        content = json.dumps(request)
        message = f"Content-Length: {len(content)}\r\n\r\n{content}"
        print(f"Sending: {request.get('method', request.get('id'))}", file=sys.stderr)
        process.stdin.write(message)
        process.stdin.flush()

    def read_response():
        """Read one LSP message."""
        # Read headers
        headers = {}
        while True:
            line = process.stdout.readline()
            if not line:
                return None
            if line == '\r\n':
                break
            if ':' in line:
                key, value = line.split(':', 1)
                headers[key.strip()] = value.strip()

        if 'Content-Length' not in headers:
            return None

        # Read content
        content_length = int(headers['Content-Length'])
        content = process.stdout.read(content_length)
        return json.loads(content)

    try:
        # Initialize
        init_request = {
            "jsonrpc": "2.0",
            "id": 1,
            "method": "initialize",
            "params": {
                "processId": None,
                "rootUri": f"file://{project_root}",
                "capabilities": {},
                "initializationOptions": {
                    "productKey": "claude-code",
                    "telemetryStorage": "Not used",
                    "productName": "Claude Code",
                    "productVersion": "0.0.1",
                    "showVerboseLogs": True
                }
            }
        }

        send_request(init_request)

        # Read responses with timeout
        print("Waiting for initialize response...", file=sys.stderr)
        response = read_response()
        if response:
            print(f"Got response: {response.get('id')}", file=sys.stderr)

        # Send initialized notification
        send_request({
            "jsonrpc": "2.0",
            "method": "initialized",
            "params": {}
        })

        # Open document
        with open(file_path, 'r') as f:
            content = f.read()

        send_request({
            "jsonrpc": "2.0",
            "method": "textDocument/didOpen",
            "params": {
                "textDocument": {
                    "uri": file_uri,
                    "languageId": "python",
                    "version": 1,
                    "text": content
                }
            }
        })

        # Wait for diagnostics notification
        print("Waiting for diagnostics...", file=sys.stderr)
        diagnostics = []
        for _ in range(10):  # Try reading up to 10 messages
            response = read_response()
            if response:
                print(f"Got message: {json.dumps(response, indent=2)}", file=sys.stderr)
                if response.get("method") == "textDocument/publishDiagnostics":
                    diagnostics.append(response)
            time.sleep(0.5)

        return diagnostics

    finally:
        process.terminate()
        try:
            process.wait(timeout=2)
        except subprocess.TimeoutExpired:
            process.kill()


if __name__ == "__main__":
    if len(sys.argv) < 2:
        print("Usage: simple_analyze.py <file_path>")
        sys.exit(1)

    results = analyze_file_simple(sys.argv[1])
    print("\n=== DIAGNOSTICS ===")
    print(json.dumps(results, indent=2))
